
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DriverWSImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/ws/driver?wsdl")
public class DriverWSImplService
    extends Service
{

    private final static URL DRIVERWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRIVERWSIMPLSERVICE_EXCEPTION;
    private final static QName DRIVERWSIMPLSERVICE_QNAME = new QName("http://ws/", "DriverWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/driver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRIVERWSIMPLSERVICE_WSDL_LOCATION = url;
        DRIVERWSIMPLSERVICE_EXCEPTION = e;
    }

    public DriverWSImplService() {
        super(__getWsdlLocation(), DRIVERWSIMPLSERVICE_QNAME);
    }

    public DriverWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRIVERWSIMPLSERVICE_QNAME, features);
    }

    public DriverWSImplService(URL wsdlLocation) {
        super(wsdlLocation, DRIVERWSIMPLSERVICE_QNAME);
    }

    public DriverWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRIVERWSIMPLSERVICE_QNAME, features);
    }

    public DriverWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DriverWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DriverWS
     */
    @WebEndpoint(name = "DriverWSImplPort")
    public DriverWS getDriverWSImplPort() {
        return super.getPort(new QName("http://ws/", "DriverWSImplPort"), DriverWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DriverWS
     */
    @WebEndpoint(name = "DriverWSImplPort")
    public DriverWS getDriverWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "DriverWSImplPort"), DriverWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRIVERWSIMPLSERVICE_EXCEPTION!= null) {
            throw DRIVERWSIMPLSERVICE_EXCEPTION;
        }
        return DRIVERWSIMPLSERVICE_WSDL_LOCATION;
    }

}
