
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DriverWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DriverWS {


    /**
     * 
     * @return
     *     returns client.Driver
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDriver", targetNamespace = "http://ws/", className = "client.FindDriver")
    @ResponseWrapper(localName = "findDriverResponse", targetNamespace = "http://ws/", className = "client.FindDriverResponse")
    @Action(input = "http://ws/DriverWS/findDriverRequest", output = "http://ws/DriverWS/findDriverResponse")
    public Driver findDriver();

    /**
     * 
     * @return
     *     returns java.util.List<client.Driver>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllDrivers", targetNamespace = "http://ws/", className = "client.FindAllDrivers")
    @ResponseWrapper(localName = "findAllDriversResponse", targetNamespace = "http://ws/", className = "client.FindAllDriversResponse")
    @Action(input = "http://ws/DriverWS/findAllDriversRequest", output = "http://ws/DriverWS/findAllDriversResponse")
    public List<Driver> findAllDrivers();

}
